apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-app-with-deploy
  namespace: apps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollout-app-with-deploy
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-for-rollout
  strategy:
    canary:
      maxUnavailable: 100%
      maxSurge: 100%
      steps:
        - setWeight: 100
